## NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:
* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy provides an N-dimensional array type, the ndarray, which describes a collection of “items” of the same type. 

The training below is adopted from the [numpy](http://www.numpy.org/) online reference

## Learning Outcomes

At the end of the workshop, students would have gained an appreciate and hand-ons practical experience on the following topics:
* Importing numpy
* arange
* type
* methods
* Matrices
* Basic Operations
* Indexing, slicing, and iterating
* Shape manipulation
* Stacking together different arrays
* Broadcasting
* Special built-in functions
  * ones
  * zeros
  * empty
  * random
  * eye

### Importing Numpy

In [1]:
import numpy as np

### arange

In [2]:
x = np.arange(9) # Generate 9 integers starting from 0 sequentially
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### type

In [3]:
type(x)

numpy.ndarray

### methods

In [4]:
x.shape

(9L,)

In [5]:
x.ndim

1

In [6]:
x.dtype.name

'int32'

In [7]:
x.itemsize

4

In [8]:
x.size

9

### Multidimensional array or Matrices

In [9]:
x = x.reshape(3,3)

In [10]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
x = np.array([(3., 6, 9), (0, 2, 4)]) 
# another way to create an ndarray is by using np.array()

In [12]:
x

array([[ 3.,  6.,  9.],
       [ 0.,  2.,  4.]])

\begin{equation*}
x = \begin{bmatrix} 3. & 6. & 9. \\ 0. & 2. & 4. \end{bmatrix}
\end{equation*}

### Basic Operations

In [13]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [14]:
c = a-b
c

array([20, 29, 38, 47])

In [15]:
b**2

array([0, 1, 4, 9])

In [16]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [17]:
a<35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method:

In [18]:
A = np.array( [[1,1],
            [0,1]] )

In [19]:
B = np.array( [[2,0],
            [3,4]] )

In [20]:
A

array([[1, 1],
       [0, 1]])

In [21]:
B

array([[2, 0],
       [3, 4]])

In [22]:
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [23]:
A.dot(B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [24]:
np.dot(A, B)                # another matrix product

array([[5, 4],
       [3, 4]])

In [25]:
a = np.random.randint(0,10,size=6).reshape(2,3)
a

array([[3, 8, 9],
       [7, 1, 2]])

In [26]:
a.sum()

30

In [27]:
a.min()

1

In [28]:
a.max()

9

In [29]:
a.sum(axis=0)                            # sum of each column

array([10,  9, 11])

In [30]:
a.sum(axis=1)                            # min of each row

array([20, 10])

In [31]:
a.cumsum(axis=1)                         # cumulative sum along each row

array([[ 3, 11, 20],
       [ 7,  8, 10]])

### Indexing, Slicing and Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [32]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [33]:
a[2]

8

In [34]:
a[2:5]

array([ 8, 27, 64])

In [35]:
a[2:5] = 999

In [36]:
a

array([  0,   1, 999, 999, 999, 125, 216, 343, 512, 729])

### Shape Manipulation

Changing the shape of an array

In [37]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 4.,  4.,  2.,  7.],
       [ 8.,  2.,  9.,  8.],
       [ 1.,  0.,  1.,  1.]])

In [38]:
a.shape

(3L, 4L)

In [39]:
a.ravel() # flatten the array

array([ 4.,  4.,  2.,  7.,  8.,  2.,  9.,  8.,  1.,  0.,  1.,  1.])

In [40]:
a.shape = (6, 2)
a

array([[ 4.,  4.],
       [ 2.,  7.],
       [ 8.,  2.],
       [ 9.,  8.],
       [ 1.,  0.],
       [ 1.,  1.]])

In [41]:
a.T

array([[ 4.,  2.,  8.,  9.,  1.,  1.],
       [ 4.,  7.,  2.,  8.,  0.,  1.]])

### Stacking together different arrays

In [42]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 4.,  9.],
       [ 8.,  1.]])

In [43]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 6.,  1.],
       [ 7.,  5.]])

In [44]:
np.vstack((a,b))

array([[ 4.,  9.],
       [ 8.,  1.],
       [ 6.,  1.],
       [ 7.,  5.]])

In [45]:
np.hstack((a,b))

array([[ 4.,  9.,  6.,  1.],
       [ 8.,  1.,  7.,  5.]])

### Broadcasting

The term **[broadcasting](https://docs.scipy.org/doc/numpy-dev/user/basics.broadcasting.html)** describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [46]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([ 2.,  4.,  6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [47]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([ 2.,  4.,  6.])

### Special built in functions

In [48]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [49]:
np.zeros((4,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [50]:
np.empty((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [51]:
x = np.random.random(9).reshape(3,3)
x

array([[ 0.32517662,  0.48167638,  0.15424493],
       [ 0.7315962 ,  0.06862411,  0.74969355],
       [ 0.35744349,  0.14137661,  0.73612688]])

In [52]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Basic Functions

In [53]:
np.linspace(0, 3, 13)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,
        2.25,  2.5 ,  2.75,  3.  ])

In [54]:
x,y = np.meshgrid([0,1,2,3,4],[0,1,2])

In [55]:
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [56]:
y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [57]:
np.r_[0:5:1]

array([0, 1, 2, 3, 4])

In [58]:
np.c_[0:5:1]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [59]:
np.around(x, 2)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [60]:
np.floor(x)             # rounds to the next smallest integer

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [61]:
np.ceil(x)              # rounds to the next largest integer

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

Other useful functions are

* sum
* cumsum
* prod
* cumprod
* diff
* unique
* sort
* max
* min